### ISSUE TITLE
Duplicate messages when send

### ISSUE THREAD

**Issue by maikealame** [xaamin/whatsapi#13]
Hey, other strange error when has more than 1 message to send:

```
$to = new \stdClass;
$to->name = 'Maike';
$to->phone = 'XXXXXXXXXXX';
$to->message = "message 1 ";
$sended = Whatsapi::send($to->message, function ($send) use ($to) {
                $send->to($to->phone);
                sleep(1);
                $send->message($to->message);
});
sleep(2);
$to->message = "second message";
$sended = Whatsapi::send($to->message, function ($send) use ($to) {
                $send->to($to->phone);
                sleep(3);
                $send->message($to->message);
});
```

In App from who received, the messages arrive in this order:
message 1
message 1
message 1
message 1
second message
second message
message 1
message 1
second message
second message

After, my chip is blocked, maybe the responsible for this is the time: in few seconds (~10) this sended 10 messages. So, I don't know what caused this, but my experience served to help fix before others blocks.

**Comment by xaamin** [comment]
You are send the same message twice. Using`$to->message` sets the message to be send in send method and you set the same, again, in closure so is added to messages queue.

```
$to = new \stdClass;
$to->name = 'Maike';
$to->phone = 'XXXXXXXXXXX';
$to->message = "message 1 ";
// Using $to->message sets the message to be send in send method
$sended = Whatsapi::send($to->message, function ($send) use ($to) {
                $send->to($to->phone);
                sleep(1);
                // This is unneccesary because send the same message twice
                // $send->message($to->message);
                // Comment or remove the above
});
sleep
```

**Comment by maikealame** [comment]
Now I understand the closure in messageManager, thanks. Some way to reset the queue ? because this can send one now and more other message in some location of script to same phone or different.

**Comment by maikealame** [comment]
Looks like catch same error:

```
$to = new \stdClass;
$to->name = 'Maike';
$to->phone = 'XXXXXXXXXXX';
$to->message = "message 1 ";
$sended = Whatsapi::send($to->message, function ($send) use ($to) {
                $send->to($to->phone);
});
sleep(2);
$to->message = "second message";
$sended = Whatsapi::send($to->message, function ($send) use ($to) {
                $send->to($to->phone);
});
```

message 1
message 1
second message
message 1
second message

**Comment by maikealame** [comment]
No luck today with this error. It's like you say, can be the closure or problem in chat-api messagestore db.

**Comment by xaamin** [comment]
I'll fix this. Wait a little time for next release.

**Comment by xaamin** [comment]
Fixed in  [v1.1.2](https://github.com/xaamin/whatsapi/releases/tag/v1.1.2)

**Comment by maikealame** [comment]
Got this error, but detail: I using the branch master of Chat-API !

```
PHP Fatal error:  Call to undefined method Xaamin\Whatsapi\MessageManager::clear() in C:\www\Syonet\whatscenter\vendor\xaamin\whatsapi\src\Clients\MGP25.php on line 186


  [Symfony\Component\Debug\Exception\FatalErrorException]
  Call to undefined method Xaamin\Whatsapi\MessageManager::clear()
```

UPDATE:
Forget this, I not updated all project, that method is from messageManager. Testing now, Thanks.

**Comment by maikealame** [comment]
Great !
