### ISSUE TITLE
New version Chat-api

### ISSUE THREAD

**Issue by maikealame** [xaamin/whatsapi#14]
Got new version: https://github.com/mgp25/Chat-API/tree/v3.2.0.1

But, it seem there is a problem with the online / offline methods in mgp25 ! In whatsProt, method sendPresenc it's no more available. See here:
https://github.com/mgp25/Chat-API/commit/a0300512a1d42dbc624b0e496b996dd02e1e64ff

Just commented this and back to normal

**Comment by xaamin** [comment]
See [1.1.5](https://github.com/xaamin/whatsapi/releases/tag/v1.1.5) versión. I try to fix this with the proper methods but Whatsapp blocked my SIM.
I hope this helps... and works.
=)

**Comment by xaamin** [comment]
Please re-read the README for changes.
