### ISSUE TITLE
Events

### ISSUE THREAD

**Issue by maikealame** [xaamin/whatsapi#18]
Help man.
Can provide some one example of events use ? Or it's like in Chat-API where we update their file ?
Thanks again.

**Comment by xaamin** [comment]
It's like in Chat-Api, you can use 

```
// With some object class instance
Whatsapi::gateway()->eventManager()->bind($event, [$this, $event]);

// With global function
Whatsapi::gateway()->eventManager()->bind($event, 'onMessageFuntionHandlerName');

```

The class `Xaamin\Whatsapi\Events\Listener` is a showcase to do that. At this time it's the only way, using legacy events.

See the full list of all events in https://github.com/mgp25/Chat-API/wiki/WhatsAPI-Documentation#list-of-all-events

**Comment by maikealame** [comment]
It's yet confused, can be used to trigger some function every time I'm get a message ?
i.e
call someFunction() when getNewMessage ?
Sorry for the noobest question, but even in the chatAPI could find this answer.

**Comment by xaamin** [comment]
Aja. You can subscribe listeners to the ChatApi event manager, this can be a class, or method name as string. 
The class Xaamin\Whatsapi\Events\Listener can you help to understand how to subscribe an object class instance .
Or if you prefer you can use global functions, see more at https://github.com/mgp25/Chat-API/wiki/WhatsAPI-Documentation#using-events
