### ISSUE TITLE
You must provide config details in order to use Whatsapi Registration Tool

### ISSUE THREAD

**Issue by nefyodovka** [xaamin/whatsapi#20]
I try to register my phone number. And I have whatsapi.php in config directory ..

But

UnexpectedValueException in WhatsapiTool.php line 17: You must provide config details in order to use Whatsapi Registration Tool

 in WhatsapiTool.php line 17
at WhatsapiTool::create()
at forward_static_call_array(array('Xaamin\Whatsapi\Facades\Native\WhatsapiTool', 'create'), array()) in Facade.php line 23
at Facade::instance() in Facade.php line 40
at Facade::__callStatic('requestCode', array('770********1', 'sms')) in RegisterController.php line 20
at RegisterController->requestCode()
at call_user_func_array(array(object(RegisterController), 'requestCode'), array()) in Controller.php line 80

**Comment by xaamin** [comment]
Are you using Laravel? If yes then see documentation to publish config files right way.
If not, you need to read documentation for non laravel users, here is it:

Configuration

Non Laravel users

If you're using another Framework, different from Laravel, you must put manually the config file `Config/config.php` on the right path.

```
    // Include the composer autoload file
    include_once "vendor/autoload.php";

    // Import the necessary classes
    use Xaamin\Whatsapi\Facades\Native\Whatsapi;
    use Xaamin\Whatsapi\Facades\Native\Registration;

    // Or, if you want you can add a class alias
    // class_alias('Xaamin\Whatsapi\Facades\Native\Whatsapi', 'Whatsapi');
    // class_alias('Xaamin\Whatsapi\Facades\Native\Registration', 'Registration');
```

Now, we tell Whatsapi about the config values.

```
    // Of course, you can use the Config class from your favorite Framework.
    $config = __DIR__ . 'config/whatsapi.php';

    Whatsapi::setConfig($config);
```

**Comment by nefyodovka** [comment]
Yes, I am using laravel. And I have already published a config file:

php artisan vendor:publish --provider="Xaamin\Whatsapi\WhatsapiServiceProvider" --tag="config"

But I have same problem.

**Comment by nefyodovka** [comment]
I am using Laravel 5.2

**Comment by xaamin** [comment]
Can you put here some code? The block code where you are registering the phone number and the use statements at the top of your controller.

**Comment by nefyodovka** [comment]
I found out what the problem is. I changed

use Xaamin\Whatsapi\Facades\Native\WhatsapiTool;
to
use WhatsapiTool

Thank you. I've already sent a message via WhatsApp

PS Sorry for my English

**Comment by xaamin** [comment]
No problem. I'm learning english as well.

**Comment by Samoht1** [comment]
I had this problem too but after setting it to use WhatsapiTool i get [status] => fail [reason] => old_version

please help

**Comment by wassimhattab** [comment]
I had this problem too but after setting it to use WhatsapiTool i get [status] => fail [reason] => old_version

please help
