### ISSUE TITLE
crypto extension is required to support encryption and don't get blocked

### ISSUE THREAD

**Issue by MSalah1** [xaamin/whatsapi#21]
When i try to send massage I got this error

crypto extension is required to support encryption and don't get blocked. See more at https://github.com/mgp25/Chat-API/wiki/Dependencies

How can I setup crypto with xampp ?

**Comment by xaamin** [comment]
Pre-Compiled extensions (Curve25519 and protobuf) for Windows users:

[Curve25519](https://github.com/mgp25/curve25519-php/raw/master/bin/win-php5.6/curve25519-php_x86.zip)
[PHP Protobuf](https://github.com/mgp25/curve25519-php/raw/master/bin/win-php5.6/php-protobuf_x86.zip)

Install and add to modules in your php.ini file

**Comment by MSalah1** [comment]
I move files to 

> C:\xampp\php\ext

and added the entry for the dll in php.ini
`extension=php_curve25519_nts.dll
extension=php_curve25519_ts.dll
extension=php_protobuf_nts.dll
extension=php_protobuf_ts.dll`

But still i got error

**Comment by MSalah1** [comment]
i install it but i got those errors

Warning: PHP Startup: Unable to load dynamic library 'C:\xampp\php\ext\php_curve25519_nts.dll' - The specified module could not be found.
 in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library 'C:\xampp\php\ext\php_protobuf_nts.dll' - The specified module could not be found.
 in Unknown on line 0

**Comment by romanopablo** [comment]
Im having the same error "curve25519 extension is required to support encryption and don't get blocked" and i have it installed and activated. 
PD: im using a docker cluster from a image provided by https://github.com/Shaked/docker-whatsapp.

**Comment by luckys383** [comment]
hi @xaamin how I resolve this issue in ubuntu? please provide me some command to install this extension I'm using php 7.1 on ubuntu 14.04.

**Comment by pkaec** [comment]
I am using mac os how to solve above problem please any one help me out. Thank you in advance
