### ISSUE TITLE
socket_write(): unable to write to socket [10053]

### ISSUE THREAD

**Issue by MSalah1** [xaamin/whatsapi#22]
Hello,

when i trying to send new message I got this error

```
ErrorException in whatsprot.class.php line 2748:
socket_write(): unable to write to socket [10053]: An established connection was aborted by the software in your host machine.
```

I'm using:
- win10 x86
- xampp v3.1.2
- php v 5.6.11

Send Controller

```
$massage = "Thanks for subscribe";

Whatsapi::send($massage, function ($send) {

            $user = User::Find(1);

            $send->to($user->phone);

}
```

**Comment by xaamin** [comment]
Iin most of the cases this exception indicates something on your machine is blocking your connection. Try running it with firewall/antivirus disabled.

**Comment by maikealame** [comment]
Same error here. In Ubuntu 16 + php 5.6, what's can be ?

**Comment by Razorhunter** [comment]
Hi, I already turn off my firewall and antivirus, still got the same exception. can someone help me on this? I'm using xamp 3.2.2 with PHP 5.6 and laravel 5.3

**Comment by Lavkushwaha** [comment]
![in the xampp apache config you will get php.ini you have to do is uncomment this socket extension shown in image and restart apache server here you go  👍  ](https://cloud.githubusercontent.com/assets/13220405/21471633/02e1849c-cade-11e6-899e-4ae0a62b1be6.png)

[in the xampp apache config you will get php.ini you have to do is uncomment this socket extension shown in image and restart apache server here you go  👍

**Comment by Lavkushwaha** [comment]
[in the xampp apache config you will get php.ini you have to do is uncomment this socket extension shown in image and restart apache server here you go  👍

**Comment by rahmani-djamel** [comment]
hi i'm still face this issue using windows 7 i try to find extension in php.ini (7.14) but i can't find it there's way to slove it ?
