### ISSUE TITLE
Laravel 5

### ISSUE THREAD

**Issue by tomswinkels** [xaamin/whatsapi#23]
Hi,

When is there some support for Laravel 5?

**Comment by xaamin** [comment]
It was designed to work with laravel 5.x, I use it on Laravel 5.1.

**Comment by AleemShaukat** [comment]
Hi Xaamin 
i am new in Laravel and php .Kindly make a short video how to integrate your package with laravel . i read your documentation and got lot of errors, kindly help the freshers
