### ISSUE TITLE
Error install package

### ISSUE THREAD

**Issue by tegarkurniawan** [xaamin/whatsapi#26]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - xaamin/whatsapi v1.1.0 requires whatsapp/chat-api ^3.2 -> satisfiable by whatsapp/chat-api[v3.2, v3.2.0.1].
    - xaamin/whatsapi v1.1.2 requires whatsapp/chat-api ^3.2 -> satisfiable by whatsapp/chat-api[v3.2, v3.2.0.1].
    - xaamin/whatsapi v1.1.5 requires whatsapp/chat-api ^3.2 -> satisfiable by whatsapp/chat-api[v3.2, v3.2.0.1].
    - xaamin/whatsapi v1.1.6 requires whatsapp/chat-api ^3.2 -> satisfiable by whatsapp/chat-api[v3.2, v3.2.0.1].
    - xaamin/whatsapi v1.1.7 requires whatsapp/chat-api ^3.2 -> satisfiable by whatsapp/chat-api[v3.2, v3.2.0.1].
    - xaamin/whatsapi v1.1.8 requires whatsapp/chat-api ^3.2 -> satisfiable by whatsapp/chat-api[v3.2, v3.2.0.1].
    - whatsapp/chat-api v3.2.0.1 requires ext-curl * -> the requested PHP extension curl is missing from your system.
    - whatsapp/chat-api v3.2 requires ext-curl * -> the requested PHP extension curl is missing from your system.
    - Installation request for xaamin/whatsapi ^1.1 -> satisfiable by xaamin/whatsapi[v1.1.0, v1.1.2, v1.1.5, v1.1.6, v1.1.7, v1.1.8].

  To enable extensions, verify that they are enabled in those .ini files:
    - /etc/php/5.6/cli/php.ini
    - /etc/php/5.6/cli/conf.d/10-mysqlnd.ini
    - /etc/php/5.6/cli/conf.d/10-opcache.ini
    - /etc/php/5.6/cli/conf.d/10-pdo.ini
    - /etc/php/5.6/cli/conf.d/15-xml.ini
    - /etc/php/5.6/cli/conf.d/20-calendar.ini
    - /etc/php/5.6/cli/conf.d/20-ctype.ini
    - /etc/php/5.6/cli/conf.d/20-dom.ini
    - /etc/php/5.6/cli/conf.d/20-exif.ini
    - /etc/php/5.6/cli/conf.d/20-fileinfo.ini
    - /etc/php/5.6/cli/conf.d/20-ftp.ini
    - /etc/php/5.6/cli/conf.d/20-gettext.ini
    - /etc/php/5.6/cli/conf.d/20-iconv.ini
    - /etc/php/5.6/cli/conf.d/20-json.ini
    - /etc/php/5.6/cli/conf.d/20-mbstring.ini
    - /etc/php/5.6/cli/conf.d/20-mcrypt.ini
    - /etc/php/5.6/cli/conf.d/20-mongo.ini
    - /etc/php/5.6/cli/conf.d/20-mysql.ini
    - /etc/php/5.6/cli/conf.d/20-mysqli.ini
    - /etc/php/5.6/cli/conf.d/20-pdo_mysql.ini
    - /etc/php/5.6/cli/conf.d/20-phar.ini
    - /etc/php/5.6/cli/conf.d/20-posix.ini
    - /etc/php/5.6/cli/conf.d/20-readline.ini
    - /etc/php/5.6/cli/conf.d/20-shmop.ini
    - /etc/php/5.6/cli/conf.d/20-simplexml.ini
    - /etc/php/5.6/cli/conf.d/20-sockets.ini
    - /etc/php/5.6/cli/conf.d/20-sysvmsg.ini
    - /etc/php/5.6/cli/conf.d/20-sysvsem.ini
    - /etc/php/5.6/cli/conf.d/20-sysvshm.ini
    - /etc/php/5.6/cli/conf.d/20-tokenizer.ini
    - /etc/php/5.6/cli/conf.d/20-wddx.ini
    - /etc/php/5.6/cli/conf.d/20-xmlreader.ini
    - /etc/php/5.6/cli/conf.d/20-xmlwriter.ini
    - /etc/php/5.6/cli/conf.d/20-xsl.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

Installation failed, reverting ./composer.json to its original content.

**Comment by xaamin** [comment]
You do not have curl extension for PHP enabled. 
- whatsapp/chat-api v3.2 requires ext-curl * -> the requested PHP extension curl is missing from your system.

Do some research in google about how to install php curl extension in your system and enable it.
