### ISSUE TITLE
undefined method Registration::eventManager()

### ISSUE THREAD

**Issue by betaselect** [xaamin/whatsapi#3]
hi @xaamin  ,

Today i did a fresh install of package. However i can't get the the registration to work properly. 

Right out of the box i get:

FatalErrorException in Listener.php line 92:
Call to undefined method Xaamin\Whatsapi\Facades\Laravel\Registration::eventManager()

I have properly registered the serviceprovider and the aliases. And have used the following code in my controller:

``` php


<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use Registration;

class PagesController extends Controller
{

    public function test()
    {

        $number = '31682092211'; # Number with country code
        $type   = 'sms'; # This can be either sms or voice

        $response = Registration::requestCode($number, $type);

    }

}

```

Did i stumble upon a bug or am I just overlooking something I did wrong? Tnx for your input!

**Comment by marcorivm** [comment]
+1 :(

**Comment by xaamin** [comment]
Change the facade alias name for `Registration => 'Xaamin\Whatsapi\Facades\Laravel\Registration'` to `'WhatsapiTool'    => 'Xaamin\Whatsapi\Facades\Laravel\Registration'` in your `config/app.php` file because **Registration** cause class name collision. I fix this issue in documentation.

Only use as 

```
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use WhatsapiTool;

class PagesController extends Controller
{

    public function test()
    {

        $number = '31682092211'; # Number with country code
        $type   = 'sms'; # This can be either sms or voice

        $response = WhatsapiTool::requestCode($number, $type);

    }

}
```

and your code must work now.

**Comment by marcorivm** [comment]
Thx, seems to be working now
