### ISSUE TITLE
Error: Failed Registration Reson Old Version

### ISSUE THREAD

**Issue by ivanjpolanco** [xaamin/whatsapi#30]
Hey,

Im having this error

Failed Registration Reson Old Version.

Is registration blocked? If not, how can i solve this.

Thank you.

**Comment by Samoht1** [comment]
I get this when requesting the register code,
please help

**Comment by jayjobanputra** [comment]
same issue face for old version ,any solution ?

**Comment by norhanelnezamy** [comment]
same issue for request the code. old version ,any solution ?

**Comment by AlexanderZon** [comment]
same issue for request the code

**Comment by samirqh** [comment]
@ivanjpolanco @sabre96 @jayjobanputra @norhanelnezamy @AlexanderZon 
to solve the old_version issue you need to do the following
1- go to the folder and open the Constants.php file.
whatsapidemo\vendor\whatsapp\chat-api\src\Constants.php

2- in the line 28 you find the following code
`const WHATSAPP_VER_CHECKER = 'https://coderus.openrepos.net/whitesoft/whatsapp_scratch'; // Check WhatsApp version`
copy the link `'https://coderus.openrepos.net/whitesoft/whatsapp_scratch'` and put it in browser and click go

the page result will be like this

> {
> "a": "15fm/PEjUZd8AxcPN4NiCw==",
> "b": "PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk",
> "c": "1478194306452L",
> "d": "2.17.413",
> "e": "2.16.12",
> "f": "2.11.634",
> "g": "PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk",
> "h": "1478194472015L",
> "i": "PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk",
> "j": "1478194472015L"
> }

3- copy the current version in value of "d" and update the line 22 in Constants.php
` const WHATSAPP_VER = '2.17.413';       // The WhatsApp version.`

4- also update the line 27 in same file Constants.php after `WhatsApp/` put the new version code
`const WHATSAPP_USER_AGENT = 'WhatsApp/2.17.413 Android/4.3 Device/Xiaomi-HM_1SW';        // User agent used in request/registration code.`

5- Finally, open the file token.php in the same path
xaamin\vendor\whatsapp\chat-api\src\token.php
and update line 10, 
`      $classesMd5 = '15fm/PEjUZd8AxcPN4NiCw=='; `
with new MD5 code, you can take form the above result in step 2 infront of value of "a"
save the changes and you can run the code with successful
