### ISSUE TITLE
ErrorException in Registration.php line 496:

### ISSUE THREAD

**Issue by badrusalsyihab** [xaamin/whatsapi#32]
ErrorException in Registration.php line 496:
"storage/whatsapi/phone-id-6281287679290.dat): failed to open stream: No such file or directory"

and I have quetion about config.php, I have see config.php in line account he have **password** 
'default'   => array(
            'nickname' => 'Itnovado',
            'number'   => '5219512132132',
            **'password' => '==87Vf4plh+lvOAvoURjBoKDKwciw='**
        ),
**how I can get my password**  & I have read in documentation and I have download WART.exe and then when I gnereted request code it's dosent work /  always bad token, can you help ?

**Comment by caiomcoliveira** [comment]
create the storage directory first.

**Comment by wassimhattab** [comment]
I created the directory now i'm getting status fail and old_version..
What's the solution in this case?

**Comment by shahina-123** [comment]
i have the same error please guide us
