### ISSUE TITLE
Laravel 5.4 Publish not working.

### ISSUE THREAD

**Issue by SapneshNaik** [xaamin/whatsapi#34]
I required the package via composer and then added 
`'Xaamin\Whatsapi\WhatsapiServiceProvider'`
 to my providers array (not sure if its to be in single quotes as all others are not in single quotes). I also added the aliases like
```
'Whatsapi' => 'Xaamin\Whatsapi\Facades\Laravel\Whatsapi',
    'WhatsapiTool' => 'Xaamin\Whatsapi\Facades\Laravel\Registration',
```
but when I did 
`php artisan vendor:publish --provider="Xaamin\Whatsapi\WhatsapiServiceProvider" --tag="config"`
I got no `whatsapi.php` in my `config` dir. I tried manually copying the config file from vendor/xaamin-whatsapi but now I'm not sure as to how to use this package.

Registration should be initiated from one of the controllers right?
I am trying to do `$response = WhatsapiTool::requestCode($number, $type);` In one of my controller but I get an error as `Class 'WhatsapiTool' not found`

**Comment by AlexanderZon** [comment]
Try do this.
`php artisan cache:clear`
`php artisan config:cache`
and try again to publish
