### ISSUE TITLE
decrypt message body

### ISSUE THREAD

**Issue by ronnievisser** [xaamin/whatsapi#4]
Hi,

when getting messages the body->data node seems encrypted. what is the correct way to decrypt the message???

thanks

**Comment by xaamin** [comment]
Do you have installed this https://github.com/mgp25/Chat-API/wiki/Dependencies dependecies ?

**Comment by pedrosoares** [comment]
Eu tenho todas as dependências e recebo a seguinte mensagem: 🔒 Mensagem criptografada 🔒 Sua versão do WhatsApp não pode exibir esta mensagem. Atualize o WhatsApp em https://www.whatsapp.com/dl/ para visualizar futuras mensagens criptografadas.

**Comment by xaamin** [comment]
See issue [#11](https://github.com/xaamin/whatsapi/issues/11).
