### ISSUE TITLE
status online when use recursive functions

### ISSUE THREAD

**Issue by maikealame** [xaamin/whatsapi#9]
Hey man,

I using a improvised cron in terminal, using laravel console, like this:

`php artisan customTask`

this execute a function recursive, like this:

```
public function sync(){
$messages = Whatsapi::getNewMessages();
$send = Whatsapi::send($text);
sleep(seconds);
$this->sync();
}
```

when I look to app, the status of my number in whatsapi is online, and only go off when the php script end, i. e., when forcing in terminal because this is recursive. I will have problems with blocking because of this ?

**Comment by xaamin** [comment]
There's no way to determine when Whatsapp blocks a number.

Take a deep look at
https://github.com/mgp25/Chat-API/issues/1975
https://github.com/venomous0x/WhatsAPI/issues/757
https://github.com/venomous0x/WhatsAPI/issues/761

More at 
https://github.com/mgp25/Chat-API/issues?utf8=%E2%9C%93&q=block

**Comment by maikealame** [comment]
Ok, only to know, is there any way to make my status offline in the function ? Its make more sense when working that way

```
public function sync(){
$messages = Whatsapi::getNewMessages();
$send = Whatsapi::send($text);
    $offline = Whatsapi::disconnect();
sleep(seconds);
$this->sync();
}
```

**Comment by xaamin** [comment]
Try using `Whastapi::offline()` function to send offline status.
I hope this helps.

**Comment by maikealame** [comment]
I'll try. thanks
